name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Getting Yarn cache dir
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.X"
          scope: "@trycourier"
      - run: yarn
      # - name: Test
      #   run: yarn test
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
