name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "12.x"
          scope: "@trycourier"
          always-auth: true
      - run: yarn
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
